spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/batch_demo?useUnicode=true&characterEncoding=utf8&autoReconnection=true&serverTimezone=UTC
    username: root
    password: dho1921!036
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: mysql
  batch:
    job:
      enabled: false  # 애플리케이션 구동시 컨텍스트 내의 모든 스프링 배치 작업 자동 실행 여부 (디폴트 true)

batch-demo:
  chunk:
    size: 15